### ISSUE TITLE
Reserving atom names for protonation

### ISSUE THREAD

**Issue by keitaroyam** [wwPDB/backbone-extension#1]
I have a concern about this update. In my understanding, the names of hydrogen atoms bonded to N are changed to H1/H2/H3 during the deposition process if protonated (NH3+), while otherwise they would be named H/H2. So it would be better to reserve these names in the monomer definitions. I did not check all monomers, but for example 060 has H1 bonded to C1, which would cause a problem (an inconsistent atom name) when it comes to N-terminus.

We (Garib and me) even think that H/H2/H3 for NH3+ hydrogen atoms would be more convenient (in the sense that we only have to reserve one additional name, H3). However, in any case, it would be better not to use names that may be used in protonation variants. What do you think?

**Comment by mbage** [comment]
Hi Keitaro,

Thanks for raising this issue.

We are not planning to reserve atom names (e.g. H or H1) because this would be difficult to implement in our annotation pipeline and in many cases (e.g. for non-peptide residues) these atom names will be appropriately used at different positions in the CCD. Here are a couple of examples:
- ACE, H/H1/H2/H3 are used to identify all the hydrogen atoms
- DA, H2 is used to describe a hydrogen on the base of adenosine
- MAN, H1/H2/H3 are used to describe the sugar’s hydrogens

In the case of 060, H1 is not defined as a standardised backbone atom name and so has not been changed. In contrast, the side chain atom HA has been replaced with a new atom name because it clashes with the new backbone HA atom naming.

We don’t store protonation variants of peptide residues in the CCD library, except for the canonical amino acids. You’re right these are currently labelled H1/H2/H3, but we are actively considering updating these to H/H2/H3 as you suggest.

We haven’t standardised the naming of H3 in cases where a non-canonical residue has N protonated but we can also consider doing this.

We are very happy to set up a meeting to discuss these issues in more detail.

**Comment by keitaroyam** [comment]
Thanks for your reply. It is great to hear you are considering H/H2/H3 names.

I understood this remediation was intended to standardise the main chain atom names of peptide monomers. Different groups (nucleotides, carbohydrates, etc) would have different sets of standard atom names, which is totally fine.

I would just like all (possible) hydrogen atom names in peptide main chain to be considered too. So,
> We haven’t standardised the naming of H3 in cases where a non-canonical residue has N protonated but we can also consider doing this.

this will be greatly appreciated!

By the way, speaking of ACE, I see sometimes ACY is used instead for the modification. I wish this kind of remediation would also happen, but this would be a completely different branch.

**Comment by mbage** [comment]
Ok great, I've updated the CCDs to also standardise the H3 atoms for non-standard residues where the backbone N is protonated. 

Where possible, I've also updated the side chain atom names to remove any of the standardised backbone atom names. 

Details for the PTM remediation project haven't been publicly announced yet, but this remediation will fix the issue with ACE/ACY. All incorrectly assigned ACY CCDs will be replaced with ACE.

**Comment by keitaroyam** [comment]
Thanks, I have checked the latest version. I see 01W now has a backbone N connected to H/H2/H3 atoms, which is good!
However, for example in ZU0, H3 is bonded to the CB atom. This will be a problem when it becomes an N terminal residue. Is it possible to take care of this kind of monomers with backbone N not protonated?

In CCD, there are amino acids having backbone N protonated or not protonated - how was this difference made?

> Details for the PTM remediation project haven't been publicly announced yet, but this remediation will fix the issue with ACE/ACY. All incorrectly assigned ACY CCDs will be replaced with ACE.

This is wonderful!

**Comment by mbage** [comment]
During the OneDep annotation process, new peptide residues should be created in the neutral state (NH2 not NH3), however, there are ~8 peptide CCDs that do not follow this (e.g. APN).  We think most of these are mistakes in handling during the annotation process and so we might consider changing their charges to NH2. 

There are hundreds of peptide CCDs that contain H3 in the side chain we felt that it was best to not to attempt to remove all of these, especially as it will be very difficult to enforce when new CCDs are created. So the removal of standardised backbone atoms from the side chain includes N, H, H2, CA, HA, C, O, OXT, HXT.

**Comment by keitaroyam** [comment]
Is there a rule for naming hydrogen atoms due to protonation? For example, if the name H3 is already used, is H4 or the smallest unused number used? Or, are depositors allowed to use whatever name they want, even if different entries use different names?

**Comment by mbage** [comment]
The N-terminal protonation of non-standard polypeptide residues happens only very rarely in the archive. For all the cases I found (3 entries), the atoms on the protonated N-terminal nitrogen were labelled H1/H2/H3. It mostly occurs for NMR entries and is rare because polypeptides in NMR entries are usually capped with ACE/NME. I don't know precisely how the protonated atom naming occurs, however, due to the rarity of its occurrence, I couldn't find any cases where H3 atom name clashes were an issue.

**Comment by GaribMurshudov** [comment]
I think it would be good to have consistency. I understand PDB's priorities to deal with currently available entries. But I think internal consistency and consistency with chemistry would be good.
Of course there are fewer cases with amino acids at the end of a polypeptide. Moreover, not in all of them N or termini are really termini. However, chemically it would be consistent if we have mechanisms to deal with compounds under different conditios.  
As for amino acids: It would be good if we would have consistent naming. it means that either we use H1/H2/H3 or H/H2/H3 (I changed these naming several times to be consisent with the PDB). If in vacuum we have H/H2 then at pH 7 we add one hydrogen and it should be H3. therefore H3 should also be reserved as a part of the main chain. 

BTW: there are some neutron cases with hydrogen names: H1/H2/H3 at the N termini (they are called, confusingly, D1/D2/D3. it is another problem, we would like chemistry and experiments to be seperated. Atom names are atom names, they should not encode experiment type)

**Comment by deborahharrus** [comment]
Reserving H3 as part of the main chain is beyond the scope of this project, but I will capture that this should be included in the list of future PDB-archive-wide remediations.
