### ISSUE TITLE
Are the new flags (pdbx_backbone_atom_flag etc.) added to all new monomers?

### ISSUE THREAD

**Issue by wojdyr** [wwPDB/backbone-extension#2]
I see that monomers added after the backbone remediation (e.g. H3I, QQC, ZUT) include new flags
_chem_comp_atom.pdbx_backbone_atom_flag 
_chem_comp_atom.pdbx_n_terminal_atom_flag 
_chem_comp_atom.pdbx_c_terminal_atom_flag
even when they don't have backbone – all the flags are N.
Is it intentional?

**Comment by mbage** [comment]
Hi Marcin,

Yes this is intentional. For consistency we have added these items to all CCD definition files in the CCD dictionary. All new monomers that are created during the annotation process will also have these items added. This is consistent with our handling of other _chem_comp_atom items, including:

_chem_comp_atom.pdbx_aromatic_flag 
_chem_comp_atom.pdbx_leaving_atom_flag 

Regards,
Marcus

**Comment by wojdyr** [comment]
> Yes this is intentional. For consistency we have added these items to all CCD definition files in the CCD dictionary.

These items were added to all remediated and new monomers. Currently, they are in 2152 out of 42125 monomers.

I thought adding it to new monomers is not intentional, because IIRC it was argued that for the meaning of _chem_comp_atom.pdbx_backbone_atom_flag for nucleic acids could be different, and I remember hearing that it will be used only for monomers in protein chains. I could misremember, though.
